"""all

Revision ID: 3d8ae03110cd
Revises: 
Create Date: 2024-09-27 18:44:22.990463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d8ae03110cd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('date_closed', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('currency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('exchange_to_base_currency', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('date_closed', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dwh_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('account_type', sa.String(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(), nullable=False),
    sa.Column('unid', sa.String(), nullable=False),
    sa.Column('bus_date_from', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('quality_identificator', sa.Integer(), nullable=False),
    sa.Column('bus_date_until', sa.DateTime(), server_default=sa.text("'9999-07-01'::date"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dwh_account_balance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_balance_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('currency_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('account_balance_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('unid', sa.String(), nullable=False),
    sa.Column('posting_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('quality_identificator', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dwh_branch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('checksum', sa.String(), nullable=False),
    sa.Column('unid', sa.String(), nullable=False),
    sa.Column('bus_date_from', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('quality_identificator', sa.Integer(), nullable=False),
    sa.Column('bus_date_until', sa.DateTime(), server_default=sa.text("'9999-07-01'::date"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dwh_currency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('exchange_to_base_currency', sa.Boolean(), nullable=False),
    sa.Column('checksum', sa.String(), nullable=False),
    sa.Column('unid', sa.String(), nullable=False),
    sa.Column('bus_date_from', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('quality_identificator', sa.Integer(), nullable=False),
    sa.Column('bus_date_until', sa.DateTime(), server_default=sa.text("'9999-07-01'::date"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dwh_customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('checksum', sa.String(), nullable=False),
    sa.Column('unid', sa.String(), nullable=False),
    sa.Column('bus_date_from', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('quality_identificator', sa.Integer(), nullable=False),
    sa.Column('bus_date_until', sa.DateTime(), server_default=sa.text("'9999-07-01'::date"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dwh_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('currency_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('unid', sa.String(), nullable=False),
    sa.Column('posting_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('quality_identificator', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prestage_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('account_type', sa.String(), nullable=False),
    sa.Column('date_created', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('checksum', sa.String(), nullable=False),
    sa.Column('unid', sa.String(), nullable=False),
    sa.Column('bus_date_from', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prestage_account_balance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_balance_id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('currency_id', sa.String(), nullable=False),
    sa.Column('balance', sa.String(), nullable=False),
    sa.Column('account_balance_date', sa.String(), nullable=False),
    sa.Column('unid', sa.String(), nullable=False),
    sa.Column('posting_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prestage_branch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('date_created', sa.String(), nullable=False),
    sa.Column('date_closed', sa.String(), nullable=True),
    sa.Column('checksum', sa.String(), nullable=False),
    sa.Column('unid', sa.String(), nullable=False),
    sa.Column('bus_date_from', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prestage_currency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency_id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('exchange_to_base_currency', sa.String(), nullable=False),
    sa.Column('checksum', sa.String(), nullable=False),
    sa.Column('unid', sa.String(), nullable=False),
    sa.Column('bus_date_from', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prestage_customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('date_created', sa.String(), nullable=False),
    sa.Column('date_closed', sa.String(), nullable=True),
    sa.Column('checksum', sa.String(), nullable=False),
    sa.Column('unid', sa.String(), nullable=False),
    sa.Column('bus_date_from', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prestage_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('branch_id', sa.String(), nullable=False),
    sa.Column('currency_id', sa.String(), nullable=False),
    sa.Column('amount', sa.String(), nullable=False),
    sa.Column('success', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('unid', sa.String(), nullable=False),
    sa.Column('posting_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stage_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('account_type', sa.String(), nullable=False),
    sa.Column('date_created', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('checksum', sa.String(), nullable=False),
    sa.Column('unid', sa.String(), nullable=False),
    sa.Column('bus_date_from', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stage_account_balance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_balance_id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('currency_id', sa.String(), nullable=False),
    sa.Column('balance', sa.String(), nullable=False),
    sa.Column('account_balance_date', sa.String(), nullable=False),
    sa.Column('unid', sa.String(), nullable=False),
    sa.Column('posting_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stage_branch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('date_created', sa.String(), nullable=False),
    sa.Column('date_closed', sa.String(), nullable=True),
    sa.Column('checksum', sa.String(), nullable=False),
    sa.Column('unid', sa.String(), nullable=False),
    sa.Column('bus_date_from', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stage_currency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency_id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('exchange_to_base_currency', sa.String(), nullable=False),
    sa.Column('checksum', sa.String(), nullable=False),
    sa.Column('unid', sa.String(), nullable=False),
    sa.Column('bus_date_from', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stage_customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('date_created', sa.String(), nullable=False),
    sa.Column('date_closed', sa.String(), nullable=True),
    sa.Column('checksum', sa.String(), nullable=False),
    sa.Column('unid', sa.String(), nullable=False),
    sa.Column('bus_date_from', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stage_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('branch_id', sa.String(), nullable=False),
    sa.Column('currency_id', sa.String(), nullable=False),
    sa.Column('amount', sa.String(), nullable=False),
    sa.Column('success', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('unid', sa.String(), nullable=False),
    sa.Column('posting_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_type', sa.String(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('account_balance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('currency_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('account_balance_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['currency_id'], ['currency.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('currency_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.id'], ),
    sa.ForeignKeyConstraint(['currency_id'], ['currency.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    op.drop_table('account_balance')
    op.drop_table('account')
    op.drop_table('stage_transaction')
    op.drop_table('stage_customer')
    op.drop_table('stage_currency')
    op.drop_table('stage_branch')
    op.drop_table('stage_account_balance')
    op.drop_table('stage_account')
    op.drop_table('prestage_transaction')
    op.drop_table('prestage_customer')
    op.drop_table('prestage_currency')
    op.drop_table('prestage_branch')
    op.drop_table('prestage_account_balance')
    op.drop_table('prestage_account')
    op.drop_table('dwh_transaction')
    op.drop_table('dwh_customer')
    op.drop_table('dwh_currency')
    op.drop_table('dwh_branch')
    op.drop_table('dwh_account_balance')
    op.drop_table('dwh_account')
    op.drop_table('customer')
    op.drop_table('currency')
    op.drop_table('branch')
    # ### end Alembic commands ###
