"""fact tables2

Revision ID: 72e35b20562c
Revises: e6b31c6ad093
Create Date: 2024-09-27 11:38:33.318045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72e35b20562c'
down_revision: Union[str, None] = 'e6b31c6ad093'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account_balance', sa.Column('balance', sa.Float(), nullable=False))
    op.add_column('prestage_account_balance', sa.Column('balance', sa.String(), nullable=False))
    op.alter_column('prestage_account_balance', 'account_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prestage_account_balance', 'account_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('prestage_account_balance', 'balance')
    op.drop_column('account_balance', 'balance')
    # ### end Alembic commands ###
