"""account_balance date

Revision ID: 79085ba1e3dc
Revises: 8cf8871ac1ec
Create Date: 2024-09-26 02:30:45.824320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79085ba1e3dc'
down_revision: Union[str, None] = '8cf8871ac1ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account_balance', sa.Column('account_balance_date', sa.DateTime(), nullable=False))
    op.add_column('prestage_account_balance', sa.Column('account_balance_date', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prestage_account_balance', 'account_balance_date')
    op.drop_column('account_balance', 'account_balance_date')
    # ### end Alembic commands ###
